### ISSUE TITLE
Help understanding TODOs

### ISSUE THREAD

**Issue by thiagoperes** [michaelochs/BCScanner#1]
Hey, I'm digging into you code but I could not understand these TODOs:
- When using multiple codes together with a hud immage the animation will break when relayouting the screen (e.g. when rotating).
- Not all supported code types of AVFoundation are added to BCScanner yet. Currently supported types are: QR, UPCE, EAN8 and EAN13.

Could you give me more details?

**Comment by michaelochs** [comment]
That are the notes that have to be done before I would consider calling this library a stable version.
- When you try to scan e.g. for QR and EAN13 and supply an image to the scanner when it asks for it and than rotate the screen, the animation runs around twice as fast, basically because the old animation is not stopped. You can try this with the example app. Just build & run and rotate.
- There are some codes from AVFoundation missing. Basically just because I haven't found information on their aspect ratio yet, so I could put them in the +aspectRatioForCode: method. This method is used for layouting the image you provide as an overlay.

I try to add the aspect ratio at the weekend. But I don't know if I have some time to fix the animation.

**Comment by michaelochs** [comment]
I added more detailed issues for the open bugs and features as I am going to start working on this project again. If you are still interested in this project I would love to see feedback or help on those topics.
